In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Reading CSV**

In [2]:
df = pd.read_csv('/Users/gaurav/Downloads/zomato.csv')
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [3]:
df.shape

(51717, 17)

In [4]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [5]:
df['dish_liked'].iloc[1]

'Momos, Lunch Buffet, Chocolate Nirvana, Thai Green Curry, Paneer Tikka, Dum Biryani, Chicken Biryani'

In [6]:
df = df.drop(['url','address','phone','menu_item','dish_liked','reviews_list'], axis=1)
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [7]:
df.shape

(51717, 11)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         51717 non-null  str
 1   online_order                 51717 non-null  str
 2   book_table                   51717 non-null  str
 3   rate                         43942 non-null  str
 4   votes                        51717 non-null  int64
 5   location                     51696 non-null  str
 6   rest_type                    51490 non-null  str
 7   cuisines                     51672 non-null  str
 8   approx_cost(for two people)  51371 non-null  str
 9   listed_in(type)              51717 non-null  str
 10  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(10)
memory usage: 4.3 MB

In [9]:
df.drop_duplicates(inplace=True)
df.shape

(51609, 11)

In [10]:
# cleaning Rate column

In [11]:
df['rate'].unique()

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '3.6/5',  '4.6/5',  '4.0/5',  '4.2/5',
  '3.9/5',  '3.1/5',  '3.0/5',  '3.2/5',  '3.3/5',  '2.8/5',  '4.4/5',
  '4.3/5',    'NEW',  '2.9/5',  '3.5/5',      nan,  '2.6/5', '3.8 /5',
  '3.4/5',  '4.5/5',  '2.5/5',  '2.7/5',  '4.7/5',  '2.4/5',  '2.2/5',
  '2.3/5', '3.4 /5',      '-', '3.6 /5',  '4.8/5', '3.9 /5', '4.2 /5',
 '4.0 /5', '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
 '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5', '4.3 /5',
 '4.4 /5',  '4.9/5',  '2.1/5',  '2.0/5',  '1.8/5', '4.6 /5', '4.9 /5',
 '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5',
 '2.0 /5', '1.8 /5']
Length: 65, dtype: str

In [12]:
# def handle_rate(value):
#     if(value == 'NEW' or value =='-'):
#         return np.nan
#     else:
#         value = str(value).split('/')
#         value = value[0]

#         return float(value)

# df['rate'] = df['rate'].apply(handle_rate)
# df['rate'].unique()

In [13]:
rate = df['rate'].replace(['NEW','-'],np.nan).str.split('/')
df['rate'] = rate.str[0].astype(float)

In [14]:
df['rate'].unique()

array([4.1, 3.8, 3.7, 3.6, 4.6, 4. , 4.2, 3.9, 3.1, 3. , 3.2, 3.3, 2.8,
       4.4, 4.3, nan, 2.9, 3.5, 2.6, 3.4, 4.5, 2.5, 2.7, 4.7, 2.4, 2.2,
       2.3, 4.8, 4.9, 2.1, 2. , 1.8])

# handling null values

In [15]:
df.isna().sum()

name                               0
online_order                       0
book_table                         0
rate                           10019
votes                              0
location                          21
rest_type                        227
cuisines                          45
approx_cost(for two people)      344
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [16]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [17]:
df['rate'].mean()

np.float64(3.7001418610242847)

In [18]:
df['rate'].median()

np.float64(3.7)

In [19]:
df['rate'] = df['rate'].fillna(df['rate'].median())

In [20]:
df.isna().sum()

name                             0
online_order                     0
book_table                       0
rate                             0
votes                            0
location                        21
rest_type                      227
cuisines                        45
approx_cost(for two people)    344
listed_in(type)                  0
listed_in(city)                  0
dtype: int64

In [21]:
df.dropna(inplace=True)

In [22]:
df.isna().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [23]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [24]:
df.rename(columns={'approx_cost(for two people)':'cost_per_two', 'listed_in(type)':'listed_type', 'listed_in(city)':'listed_city'}, inplace=True)
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost_per_two,listed_type,listed_city
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [25]:
df['location'].value_counts()

location
BTM                      5056
HSR                      2494
Koramangala 5th Block    2479
JP Nagar                 2218
Whitefield               2105
                         ...
West Bangalore              6
Yelahanka                   5
Jakkur                      3
Rajarajeshwari Nagar        2
Peenya                      1
Name: count, Length: 93, dtype: int64

**cleaning cost per 2 coln**

In [26]:
df['cost_per_two'].unique()

<StringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '900',   '200',   '750',   '150',   '850',   '100', '1,200',
   '350',   '250',   '950', '1,000', '1,500', '1,300',   '199',    '80',
 '1,100',   '160', '1,600',   '230',   '130',    '50',   '190', '1,700',
 '1,400',   '180', '1,350', '2,200', '2,000', '1,800', '1,900',   '330',
 '2,500', '2,100', '3,000', '2,800', '3,400',    '40', '1,250', '3,500',
 '4,000', '2,400', '2,600',   '120', '1,450',   '469',    '70', '3,200',
    '60',   '560',   '240',   '360', '6,000', '1,050', '2,300', '4,100',
 '5,000', '3,700', '1,650', '2,700', '4,500',   '140']
Length: 70, dtype: str

In [27]:
# removing commas
df['cost_per_two'] = df['cost_per_two'].str.replace(',','').astype(int)

In [28]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost_per_two,listed_type,listed_city
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [29]:
df.dtypes

name                str
online_order        str
book_table          str
rate            float64
votes             int64
location            str
rest_type           str
cuisines            str
cost_per_two      int64
listed_type         str
listed_city         str
dtype: object

**cleaning restaurant type coln**

In [30]:
rest_types = df['rest_type'].value_counts()
rest_types

rest_type
Quick Bites                   19010
Casual Dining                 10253
Cafe                           3682
Delivery                       2574
Dessert Parlor                 2242
                              ...
Pop Up                            2
Food Court, Beverage Shop         2
Dessert Parlor, Food Court        2
Sweet Shop, Dessert Parlor        1
Quick Bites, Kiosk                1
Name: count, Length: 93, dtype: int64

In [31]:
rest_types_lessthan_500 = rest_types[rest_types>300]
rest_types_lessthan_500

rest_type
Quick Bites            19010
Casual Dining          10253
Cafe                    3682
Delivery                2574
Dessert Parlor          2242
Takeaway, Delivery      2008
Bakery                  1140
Casual Dining, Bar      1130
Beverage Shop            863
Bar                      686
Food Court               616
Sweet Shop               468
Bar, Casual Dining       411
Lounge                   395
Pub                      355
Fine Dining              345
Casual Dining, Cafe      311
Name: count, dtype: int64

In [32]:
rest_types[rest_types<200]

rest_type
Sweet Shop, Quick Bites       178
Kiosk                         176
Dessert Parlor, Cafe          175
Cafe, Casual Dining           173
Cafe, Bakery                  163
                             ...
Pop Up                          2
Food Court, Beverage Shop       2
Dessert Parlor, Food Court      2
Sweet Shop, Dessert Parlor      1
Quick Bites, Kiosk              1
Name: count, Length: 72, dtype: int64

In [33]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost_per_two,listed_type,listed_city
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [34]:
single_restaurant_types = df[~df['rest_type'].str.contains(',')]['rest_type'].value_counts()
single_restaurant_types

rest_type
Quick Bites       19010
Casual Dining     10253
Cafe               3682
Delivery           2574
Dessert Parlor     2242
Bakery             1140
Beverage Shop       863
Bar                 686
Food Court          616
Sweet Shop          468
Lounge              395
Pub                 355
Fine Dining         345
Mess                264
Kiosk               176
Takeaway            116
Food Truck           84
Confectionery        42
Dhaba                40
Club                 36
Microbrewery         30
Bhojanalya            3
Pop Up                2
Name: count, dtype: int64

In [35]:
# Function that handles ANY number of combined types
def assign_single_type(rest_type_str, single_counts):
    # If already a single type, return as-is
    if ',' not in str(rest_type_str):
        return rest_type_str.strip()
    
    # Split into individual types (works for 2, 3, or more)
    types = [t.strip() for t in rest_type_str.split(',')]
    
    # Keep only types that exist in our single-type reference
    valid_types = [t for t in types if t in single_counts.index]
    
    if not valid_types:
        return 'Other'  # fallback: just take the first one
    
    # Weighted probability based on real counts
    weights = np.array([single_counts[t] for t in valid_types], dtype=float)
    weights = weights / weights.sum()  # normalize to sum to 1
    
    return np.random.choice(valid_types, p=weights)

# Apply to entire dataset
np.random.seed(42)
df['rest_type_clean'] = df['rest_type'].apply(
    lambda x: assign_single_type(x, single_restaurant_types)
)

In [36]:
df['rest_type_clean'] = df['rest_type_clean'].replace(['Dhaba','Food Truck','Kiosk','Confectionery','Mess','Takeaway','Sweet Shop','Beverage Shop','Food Court','Bhojanalya','Pop Up'],'Other')

In [37]:
# grouping high revenue generating groups together
df['rest_type_clean'] = df['rest_type_clean'].replace(['Bar','Pub','Lounge','Fine Dining','Microbrewery','Club'],'Fine dining/Clubs')

In [38]:
df['rest_type_clean'].value_counts ()

rest_type_clean
Quick Bites          20399
Casual Dining        12686
Delivery              4499
Cafe                  4329
Other                 2854
Dessert Parlor        2695
Fine dining/Clubs     2267
Bakery                1313
Name: count, dtype: int64

In [39]:
df.groupby('rest_type_clean')['cost_per_two'].median()

rest_type_clean
Bakery                400.0
Cafe                  600.0
Casual Dining         800.0
Delivery              400.0
Dessert Parlor        300.0
Fine dining/Clubs    1500.0
Other                 250.0
Quick Bites           300.0
Name: cost_per_two, dtype: float64

In [40]:
df = df.drop('rest_type',axis=1)

In [41]:
df.head()

,name,online_order,book_table,rate,votes,location,cuisines,cost_per_two,listed_type,listed_city,rest_type_clean
0,Jalsa,Yes,Yes,4.1,775,Banashankari,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Casual Dining
1,Spice Elephant,Yes,No,4.1,787,Banashankari,"Chinese, North Indian, Thai",800,Buffet,Banashankari,Casual Dining
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Mexican, Italian",800,Buffet,Banashankari,Casual Dining
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,"South Indian, North Indian",300,Buffet,Banashankari,Quick Bites
4,Grand Village,No,No,3.8,166,Basavanagudi,"North Indian, Rajasthani",600,Buffet,Banashankari,Casual Dining

**cleaning location coln**

In [42]:
location = df['location'].value_counts(ascending=False)

In [43]:
location_less_than_200 = location[location<200]

def handle_location(value):
    if(value in location_less_than_200):
        return 'Others'
    else:
        return value

df['location'] = df['location'].apply(handle_location)
df['location'].value_counts()

location
BTM                      5056
Others                   3402
HSR                      2494
Koramangala 5th Block    2479
JP Nagar                 2218
Whitefield               2105
Indiranagar              2026
Jayanagar                1916
Marathahalli             1805
Bannerghatta Road        1609
Bellandur                1268
Electronic City          1246
Koramangala 1st Block    1236
Brigade Road             1210
Koramangala 7th Block    1174
Koramangala 6th Block    1127
Sarjapur Road            1047
Koramangala 4th Block    1017
Ulsoor                   1011
Banashankari              902
MG Road                   893
Kalyan Nagar              841
Richmond Road             803
Malleshwaram              721
Frazer Town               714
Basavanagudi              684
Residency Road            671
Brookefield               656
New BEL Road              644
Banaswadi                 640
Kammanahalli              639
Rajajinagar               591
Church Street             566
Lavelle Road              518
Shanti Nagar              508
Shivajinagar              498
Cunningham Road           490
Domlur                    482
Old Airport Road          437
Ejipura                   433
Commercial Street         370
St. Marks Road            343
Koramangala 8th Block     294
Vasanth Nagar             293
Jeevan Bhima Nagar        268
Wilson Garden             246
Bommanahalli              236
Koramangala 3rd Block     215
Name: count, dtype: int64

In [44]:
df.head()

,name,online_order,book_table,rate,votes,location,cuisines,cost_per_two,listed_type,listed_city,rest_type_clean
0,Jalsa,Yes,Yes,4.1,775,Banashankari,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Casual Dining
1,Spice Elephant,Yes,No,4.1,787,Banashankari,"Chinese, North Indian, Thai",800,Buffet,Banashankari,Casual Dining
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Mexican, Italian",800,Buffet,Banashankari,Casual Dining
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,"South Indian, North Indian",300,Buffet,Banashankari,Quick Bites
4,Grand Village,No,No,3.8,166,Basavanagudi,"North Indian, Rajasthani",600,Buffet,Banashankari,Casual Dining

In [45]:
cuisines = df['cuisines'].value_counts()
cuisines_less_than_100 = cuisines[cuisines<100]

def handle_cuisines(value):
    if(value in cuisines_less_than_100):
        return 'Others'
    else:
        return value

df['cuisines'] = df['cuisines'].apply(handle_cuisines)
df['cuisines'].value_counts()

cuisines
Others                                 26159
North Indian                            2852
North Indian, Chinese                   2351
South Indian                            1820
Biryani                                  903
                                       ...
South Indian, Chinese, North Indian      105
North Indian, Mughlai, Chinese           104
South Indian, Fast Food                  104
Italian, Pizza                           102
North Indian, Chinese, Seafood           102
Name: count, Length: 70, dtype: int64

In [46]:
df['listed_type'].value_counts()

listed_type
Delivery              25579
Dine-out              17562
Desserts               3559
Cafes                  1703
Drinks & nightlife     1084
Buffet                  869
Pubs and bars           686
Name: count, dtype: int64

In [47]:
df['listed_city'].value_counts()

listed_city
BTM                      3239
Koramangala 7th Block    2901
Koramangala 5th Block    2799
Koramangala 4th Block    2742
Koramangala 6th Block    2588
Jayanagar                2351
JP Nagar                 2072
Indiranagar              1834
Church Street            1785
MG Road                  1780
Brigade Road             1764
HSR                      1727
Lavelle Road             1726
Marathahalli             1629
Bannerghatta Road        1600
Residency Road           1600
Whitefield               1589
Brookefield              1495
Old Airport Road         1380
Kammanahalli             1305
Kalyan Nagar             1285
Basavanagudi             1264
Sarjapur Road            1235
Electronic City          1214
Bellandur                1205
Frazer Town              1179
Malleshwaram             1092
Rajajinagar              1068
Banashankari              859
New BEL Road              735
Name: count, dtype: int64

In [48]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'location',
       'cuisines', 'cost_per_two', 'listed_type', 'listed_city',
       'rest_type_clean'],
      dtype='str')

In [49]:
df.drop_duplicates(inplace=True)

In [50]:
df.count()

name               51040
online_order       51040
book_table         51040
rate               51040
votes              51040
location           51040
cuisines           51040
cost_per_two       51040
listed_type        51040
listed_city        51040
rest_type_clean    51040
dtype: int64

In [51]:
df['cost_category'] = pd.cut(
    df['cost_per_two'],
    bins=[0, 500, 1000, float('inf')],
    labels=['Low', 'Medium', 'High']
)

In [52]:
df.to_csv("clean_zomato.csv", index=False, sep=',')

In [53]:
df_clean = pd.read_csv('clean_zomato.csv')

In [54]:
df_clean.count()

name               51040
online_order       51040
book_table         51040
rate               51040
votes              51040
location           51040
cuisines           51040
cost_per_two       51040
listed_type        51040
listed_city        51040
rest_type_clean    51040
cost_category      51040
dtype: int64

In [55]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'location',
       'cuisines', 'cost_per_two', 'listed_type', 'listed_city',
       'rest_type_clean', 'cost_category'],
      dtype='str')

In [56]:
df['rest_type_clean'].value_counts()

rest_type_clean
Quick Bites          20397
Casual Dining        12686
Delivery              4499
Cafe                  4329
Other                 2854
Dessert Parlor        2695
Fine dining/Clubs     2267
Bakery                1313
Name: count, dtype: int64

In [57]:
df[df['name'] == 'CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The Alley']

,name,online_order,book_table,rate,votes,location,cuisines,cost_per_two,listed_type,listed_city,rest_type_clean,cost_category
10,CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1,402,Banashankari,Cafe,500,Cafes,Banashankari,Cafe,Low
193,CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1,402,Banashankari,Cafe,500,Delivery,Banashankari,Cafe,Low
566,CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1,402,Banashankari,Cafe,500,Dine-out,Banashankari,Cafe,Low